import type { ReactElement } from 'react';

/**
 * Server Component that emits a `<script type="application/ld+json">` tag
 * carrying the per-request CSP nonce.
 *
 * # CSP contract
 *
 * Inline scripts on ConciergeTravel.fr live under a strict CSP3 policy:
 *
 *     script-src 'self' 'nonce-{nonce}' 'strict-dynamic'
 *
 * Any inline `<script>` (including `type="application/ld+json"`) must carry
 * the per-request nonce or it is blocked by the browser — there is no
 * `'unsafe-inline'` fallback in production. The nonce is generated by
 * `middleware.ts` (see `lib/security/csp.ts`) and exposed both as the
 * `x-nonce` request header and as the `Content-Security-Policy` nonce-source.
 *
 * # Why nonce is a required prop (vs reading `headers()` here)
 *
 * Earlier versions of this component called `headers()` internally. That had
 * two problems:
 *
 *   1. The dynamic-API call was hidden inside a leaf RSC, so pages declaring
 *      `revalidate = N` *looked* ISR-cached while in fact triggering opaque
 *      Next.js fall-throughs — `DYNAMIC_SERVER_USAGE` 500s on the hotel
 *      detail (resolved in PR #56), or — worse — silently-cached HTML with
 *      `nonce=""` that the browser then refused to execute (resolved on
 *      the home in PR #57).
 *   2. Each `<JsonLdScript>` re-resolved the same request headers, which
 *      Next.js logs as a perf warning when many of them ship on a single
 *      page.
 *
 * Requiring callers to read the nonce once at the page boundary and forward
 * it explicitly makes the request-scoped dependency visible in the page
 * file. Pages that emit JSON-LD therefore *must* be dynamic (the
 * `headers()` call at the top is what marks them as such).
 *
 * Skill: structured-data-schema-org §JSON-LD + security-engineering §CSP.
 */
interface JsonLdScriptProps {
  readonly data: unknown;
  /**
   * Per-request CSP nonce read from the `x-nonce` header set by middleware.
   * Pages typically build it as:
   *
   * ```ts
   * const nonce = (await headers()).get('x-nonce') ?? undefined;
   * ```
   *
   * `undefined` is accepted to keep callers tolerant of routes where the
   * middleware matcher excludes the request (e.g. dev tooling, internal
   * smoke endpoints). In production every page-route hits the middleware
   * so this is always a real value.
   */
  readonly nonce: string | undefined;
}

export function JsonLdScript({ data, nonce }: JsonLdScriptProps): ReactElement {
  return (
    <script
      type="application/ld+json"
      nonce={nonce}
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
