-- 0027 — Editorial v2: tables, glossary, external sources, callouts.
--
-- Phase 13 v2 — content engineering long-read.
--
-- Adds 5 structured JSONB columns to `editorial_guides` AND
-- `editorial_rankings` to support the "long-read editorial" format
-- (≥ 3500 words FR per guide / ranking):
--
--   1. `tables jsonb` — structured comparison tables. Shape:
--        [
--          {
--            key: 'seasons',                  -- stable id (kebab-case)
--            kind: 'seasons' | 'palaces_comparison' | 'distances'
--                | 'dining_michelin' | 'budget' | 'events_calendar'
--                | 'shopping' | 'activities' | 'generic',
--            title_fr, title_en,
--            note_fr, note_en,                 -- caption / disclaimer
--            headers: [{ key, label_fr, label_en, align?: 'left'|'right'|'center' }],
--            rows: [{ [headerKey]: string | number | { text, href? } }]
--          },
--          …
--        ]
--      6 tables per guide is the target sweet spot.
--
--   2. `glossary jsonb` — domain-specific micro-content:
--        [{ term_fr, term_en, definition_fr (≥ 30 words), definition_en }]
--      8-12 terms per guide (Palace, Atout France, ski-in/ski-out, etc.).
--
--   3. `external_sources jsonb` — EEAT trust signal (authoritative
--      domains the article references):
--        [{
--          url,                                 -- validated against ALLOWLIST
--          label_fr, label_en,
--          type: 'wikipedia' | 'official' | 'unesco' | 'michelin'
--              | 'atout_france' | 'tourist_office' | 'wikidata'
--              | 'press' | 'wikimedia_commons' | 'gov' | 'other'
--        }]
--      8-15 sources per guide.
--
--   4. `editorial_callouts jsonb` — sidebar boxes:
--        [{
--          kind: 'did_you_know' | 'concierge_tip' | 'warning'
--              | 'pro_tip' | 'fact',
--          title_fr, title_en,
--          body_fr (≥ 30 words), body_en
--        }]
--      3-5 callouts per guide.
--
--   5. `toc_anchors jsonb` — generated by the pipeline for SEO/UX:
--        [{ anchor, label_fr, label_en, level: 2 | 3 }]
--      Auto-derived from sections + tables + glossary anchors.
--
-- Why JSONB and not new normalized tables?
--   - These columns are read together on every guide render — a single
--     SELECT is faster than 5 joins.
--   - Payload's array field maps 1:1 to JSONB; no schema migration when
--     editorial gets a Payload-managed CMS.
--   - We never filter or aggregate on them server-side.
--
-- For `editorial_rankings` we add the same 5 columns — the LLM v2
-- pipeline produces tables (Top X comparison, criteria glossary), a
-- methodology callout, and sources & references in the same shape.
--
-- Skill: content-modeling, seo-technical §EEAT, geo-llm-optimization.

-- ============================================================================
-- editorial_guides v2 columns
-- ============================================================================

alter table public.editorial_guides
  add column if not exists tables jsonb not null default '[]'::jsonb,
  add column if not exists glossary jsonb not null default '[]'::jsonb,
  add column if not exists external_sources jsonb not null default '[]'::jsonb,
  add column if not exists editorial_callouts jsonb not null default '[]'::jsonb,
  add column if not exists toc_anchors jsonb not null default '[]'::jsonb;

comment on column public.editorial_guides.tables is
  'Structured comparison tables (seasons, palaces, distances, dining, budget, events). See migration 0027 for shape.';
comment on column public.editorial_guides.glossary is
  'Glossary of domain terms with bilingual definitions. 8-12 entries per guide.';
comment on column public.editorial_guides.external_sources is
  'EEAT trust signal: list of authoritative external URLs (Wikipedia, Atout France, UNESCO, Michelin…).';
comment on column public.editorial_guides.editorial_callouts is
  'Sidebar boxes (did_you_know, concierge_tip, warning, pro_tip, fact). 3-5 per guide.';
comment on column public.editorial_guides.toc_anchors is
  'Pre-computed table-of-contents anchors for the sticky TOC sidebar.';

-- ============================================================================
-- editorial_rankings v2 columns
-- ============================================================================

alter table public.editorial_rankings
  add column if not exists tables jsonb not null default '[]'::jsonb,
  add column if not exists glossary jsonb not null default '[]'::jsonb,
  add column if not exists external_sources jsonb not null default '[]'::jsonb,
  add column if not exists editorial_callouts jsonb not null default '[]'::jsonb,
  add column if not exists toc_anchors jsonb not null default '[]'::jsonb;

comment on column public.editorial_rankings.tables is
  'Structured comparison tables (Top X criteria, awards). See migration 0027.';
comment on column public.editorial_rankings.glossary is
  'Glossary of ranking criteria (Palace, Atout France, Michelin stars…).';
comment on column public.editorial_rankings.external_sources is
  'EEAT trust signal: list of authoritative external URLs.';
comment on column public.editorial_rankings.editorial_callouts is
  'Sidebar boxes (methodology notes, fact, warning).';
comment on column public.editorial_rankings.toc_anchors is
  'Pre-computed table-of-contents anchors.';
