-- 0030 — Editorial rankings: factual_summary (CDC §2.3, AEO).
--
-- Adds the bilingual `factual_summary_*` columns used by the
-- ranking detail page right under the H1 (visible block) and as
-- the JSON-LD `Article.description` value.
--
-- Format expected (per CDC §2.3):
--   "Sélection de N [type] [adjectif] à/en [lieu], [year]: [3 USP]."
--   Length: 130-150 chars (lint-soft, no DB CHECK so we can grow if needed).
--
-- Skill: geo-llm-optimization, structured-data-schema-org, content-modeling.

alter table public.editorial_rankings
  add column if not exists factual_summary_fr text,
  add column if not exists factual_summary_en text;

comment on column public.editorial_rankings.factual_summary_fr is
  'CDC §2.3 — IA-ready 130-150 chars summary surfaced under the H1 + injected '
  'into Article.description JSON-LD. Generated by Pass 9 of generate-ranking-v2.';

comment on column public.editorial_rankings.factual_summary_en is
  'EN sibling of factual_summary_fr. Optional in V1 (FR-only) — falls back '
  'to factual_summary_fr when the EN page renders without a translation.';

insert into public._cct_sql_migrations (filename, applied_at)
  values ('0030_editorial_rankings_factual_summary.sql', now())
  on conflict do nothing;
